version: "3.7"
services: 
  postgres:
      container_name: Postgress-graph
      image: postgres:latest
      ports: 
        - "5432:5432"
      volumes: 
        - ./pg-data:/var/lib/postgresql/data
      networks: 
        - netku
      environment: 
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=abcd1234
        - POSTGRES_DB=product

  redis:
      container_name: redis-graph
      image: redis:alpine3.12
      command: redis-server
      environment: 
        - REDIS_PORT=6379
      ports:  
        - "6767:6379"
      networks: 
        - netku
      volumes: 
        - ./redis-data:/data

  backend:
      image: dzulfikarindzar/jenkins-backend:master
      ports: 
          - "9191-9192:9100"
      environment: 
          - DBUSER=admin
          - DBPASSWORD=1234abcd
          - DBNAME=product
          - DBHOST=3.83.153.65
          - DBPORT=5432
          - JWT_KEYS=rahmazulfamufidah
          - CLOUD_KEY=916527972872257
          - CLOUD_SECRET=HvVtRuLStA9JHA_ojG4raERMLqk
          - CLOUD_NAME=warungdevops
          - REDIS_HOST=redis
          - REDIS_PORT=6379
      deploy:
       mode: replicated
       replicas: 2
       resources:
         limits:
           cpus: "0.50"
           memory: 50M
      networks: 
          - netku
      depends_on: 
          - postgres

networks: 
    netku:
        driver: bridge

volumes: 
    pg-data:
    redis-data: