version: "3.7"
services: 
  postgres:
      container_name: Postgress
      image: postgres:latest
      ports: 
        - "5050:5432"
      volumes: 
        - ./pg-data:/var/lib/postgresql/data
      networks: 
        - netku
      environment: 
        - POSTGRES_USER=dzul
        - POSTGRES_PASSWORD=dzulfikar
        - POSTGRES_DB=product

  redis:
      container_name: redis
      image: redis:alpine3.12
      command: redis-server
      environment: 
        - REDIS_PORT=6379
      ports:  
        - "9192:6379"
      networks: 
        - netku
      volumes: 
        - ./redis-data:/data

  backend:
      image: dzulfikarindzar/jenkins-backend:master
      ports: 
          - "9191:9100"
      environment: 
          - DBUSER=dzul
          - DBPASSWORD=dzulfikar
          - DBNAME=product
          - DBHOST=postgres
          - DBPORT=5432
          - JWT_KEYS=rahmazulfamufidah
          - CLOUD_KEY=916527972872257
          - CLOUD_SECRET=HvVtRuLStA9JHA_ojG4raERMLqk
          - CLOUD_NAME=warungdevops
          - REDIS_HOST=redis
          - REDIS_PORT=6379
      networks: 
          - netku
      depends_on: 
          - postgres

networks: 
    netku:
        driver: bridge

volumes: 
    pg-data:
    redis-data: