version: "3.7"
services: 
  postgres:
      container_name: Postgress
      image: postgres:latest
      ports: 
        - "5432:5432"
      volumes: 
        - ./pg-data:/var/lib/postgresql/data
      networks: 
        - netku
      environment: 
        - POSTGRES_USER=dzul
        - POSTGRES_PASSWORD=dzulfikar
        - POSTGRES_DB=product

  pgadmin:
     container_name: pgadmin
     image: dpage/pgadmin4
     ports:
        - "6789:80"
     environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: root
     restart: unless-stopped
     networks:
        - netku

  redis:
      container_name: redis
      image: redis:alpine3.12
      command: redis-server
      environment: 
        - REDIS_PORT=6379
      ports:  
        - "6379:6379"
      networks: 
        - netku
      volumes: 
        - ./redis-data:/data

  backend:
      image: dzulfikarindzar/jenkins-backend
      ports: 
          - "8002:9100"
      environment: 
          - DBUSER=dzul
          - DBPASSWORD=dzulfikar
          - DBNAME=product
          - DBHOST=postgres
          - DBPORT=5432
          - JWT_KEYS=rahmazulfamufidah
          - CLOUD_KEY=916527972872257
          - CLOUD_SECRET=HvVtRuLStA9JHA_ojG4raERMLqk
          - CLOUD_NAME=warungdevops
          - REDIS_HOST=redis
          - REDIS_PORT=6379
      networks: 
          - netku
      depends_on: 
          - postgres

networks: 
    netku:
        driver: bridge

volumes: 
    pg-data:
    redis-data: